A=100
B=200
C=A+B # Addition
D=A-B # Subtraction
E=A * B # Multiplication
F=B/A # Regular
G=B//A #Floor Division
H=A ** 3 # Exponential(power)
I=B ** 4
K=B % A # remainder
L=A % B # remainder
print("Sum of A and B=",C)
print("Difference of A and B=",D)
print("Product of A and B=",E)
print("Regular Division of B and A is=",F)
print("Floor Division of B and A is=",G)
print("result of A power 3 is =",H)
print("result of B power 4 is =",I)
print("Remainder value when B divided by A is=",K)
print("Remainder value when A divided by B is=",L)